- id: '1618669616464'
  alias: Start diverse etter restart (Nabu Casa, fades, etc.)
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: cloud.remote_connect
  - service: pyscript.reset_trans
  mode: single
- id: '1618682640574'
  alias: 'KjøkkenNest: Tving HA med bryter'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant Pi
      type: keypress
      key: InstantReplay
  condition: []
  action:
  - service: script.restart_skjerm_kjokken
  mode: single
- id: '1618682690989'
  alias: 'KjøkkenNest: Start HA med bryter'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant Pi
      type: keypress
      key: Home
  condition: []
  action:
  - service: script.trigger_view
  mode: single
- id: '1618754582616'
  alias: Keep hub on correct activity
  description: ''
  trigger:
  - platform: state
    entity_id: remote.harmony_hub_stua
    attribute: current_activity
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: remote.harmony_hub_stua
      state: Home Assistant
      attribute: current_activity
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - type: turn_on
    device_id: cadbb5e03d5e544232dc2898cfb9360c
    entity_id: switch.harmony_hub_home_assistant
    domain: switch
  mode: single
- id: '1618761509148'
  alias: Start/stopp Spotify
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant Pi
      type: keypress
      key: Play
  condition: []
  action:
  - service: media_player.media_play_pause
    target:
      entity_id: media_player.spotify_gramatus
  mode: single
- id: '1618847001623'
  alias: 'Musikk: Neste'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant Pi
      type: keypress
      key: Fwd
  condition: []
  action:
  - service: media_player.media_next_track
    target:
      entity_id: media_player.spotify_gramatus
  mode: single
- id: '1618847054162'
  alias: 'Musikk: Forrige'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant Pi
      type: keypress
      key: Rev
  condition: []
  action:
  - service: media_player.media_previous_track
    target:
      entity_id: media_player.spotify_gramatus
  mode: single
- id: '1619900466372'
  alias: Nattlys 15 min
  description: ''
  trigger:
  - platform: state
    entity_id: timer.natt_nedtelling
    to: active
  condition:
  - condition: state
    entity_id: input_select.nattlys_varighet
    state: 15 min
  action:
  - service: pyscript.turn_on_scene_by_id
    data:
      scene_id: Y2qG5PtH6AC7b1j
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: pyscript.turn_on_scene_by_id
    data:
      scene_id: xyJCA3wUDhukb-w
  - delay:
      hours: 0
      minutes: 9
      seconds: 50
      milliseconds: 0
  - service: light.turn_on
    target:
      entity_id: light.c_hue_go_soverom_1
    data:
      transition: 300
      brightness: 1
  - service: light.turn_on
    target:
      entity_id: light.c_hue_go_soverom_2
    data:
      transition: 300
      brightness: 1
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id: light.c_hue_go_soverom_1
  - service: light.turn_off
    target:
      entity_id: light.c_hue_go_soverom_2
  mode: restart
- id: '1629057762940'
  alias: 'Vekking: 30min før alarmtid (forberede vekking)'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ now().timestamp() | timestamp_custom(''%H:%M'', true) == (state_attr(''input_datetime.vekking'',
      ''timestamp'') - (30*60)) | timestamp_custom(''%H:%M'', false)}}'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_aktiv
    state: 'on'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.vekking_pagar
  - service: remote.turn_off
    target:
      entity_id: remote.harmony_hub_soverom
  - service: climate.turn_off
    target:
      entity_id: climate.soverom
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.spotify_gramatus
      state: idle
  - service: media_player.media_pause
    target:
      entity_id: media_player.spotify_gramatus
  mode: restart
- id: '1629177948654'
  alias: 'Vekking: alarmtid, men tidligst 30min før soloppgang'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.vekking
  - platform: sun
    event: sunrise
    offset: '-25'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_aktiv
    state: 'on'
  - condition: sun
    after: sunrise
    after_offset: '-30'
  - condition: time
    after: input_datetime.vekking
  action:
  - device_id: f1b95e9bf965bb365b1cf27098557194
    domain: cover
    entity_id: cover.tradfri_blind
    type: set_position
    position: 100
  mode: restart
- id: '1630215592882'
  alias: Test stuff
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.spotify_gramatus
    to: playing
  condition:
  - condition: state
    entity_id: input_boolean.vekking_pagar
    state: 'on'
  action:
  - service: spotcast.start
    data:
      entity_id: media_player.godehol
  mode: restart
- id: '1630781593162'
  alias: Fortsett avspilling når alarmen er slått av
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.nettbrett1_next_alarm
    to: unavailable
  condition: []
  action:
  - device_id: 718eb221df42df08220a669ac65aae31
    domain: light
    entity_id: light.a_kontor
    type: flash
  mode: single
- id: '1630784406319'
  alias: 'Vekking: på alarmtid (lyd)'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.vekking
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.alarm_aktivert_med_lyd
      state: 'on'
    - condition: state
      entity_id: input_boolean.alarm_aktiv
      state: 'on'
  action:
  - service: pyscript.wakeup_alarm
  mode: restart
- id: '1631038106031'
  alias: 'Vekking: restart hvis musikken ikke er på'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
    hours: '*'
    seconds: '0'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_aktivert_med_lyd
    state: 'on'
  - condition: state
    entity_id: input_boolean.vekking_pagar
    state: 'on'
    for:
      hours: 0
      minutes: 31
      seconds: 0
      milliseconds: 0
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.spotify_gramatus
      state: playing
  - condition: time
    after: input_datetime.vekking
  action:
  - service: pyscript.wakeup_alarm
  mode: restart
- id: '1631378585687'
  alias: 'Lysfade: Hoved - neste fade'
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.lysfade_neste_trigger_hoved
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: pyscript.trigger_transition_scene
    data:
      transition_group: Hoved
  mode: restart
- id: '1631381907806'
  alias: 'Lysfade: Hoved - start ny gruppe'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.lysfade_start_neste_hovedfade
  condition: []
  action:
  - service: pyscript.set_current_trans_auto
    data:
      transition_group: Hoved
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: pyscript.trigger_transition_scene
    data:
      transition_group: Hoved
  mode: restart
- id: '1631382642843'
  alias: 'LysFade: Sikre tid fra vekking til arbeidslys'
  description: ''
  trigger:
  - platform: state
    entity_id: input_datetime.huetrans_vekking_endtime
  - platform: state
    entity_id: input_datetime.huetrans_arbeidslys_endtime
  - platform: state
    entity_id: input_datetime.huetrans_basislys_dag_endtime
  - platform: state
    entity_id: input_datetime.huetrans_basislys_morgen_endtime
  condition: []
  action:
  - service: pyscript.ensure_worklight_startup
  mode: single
- id: '1631430465974'
  alias: Termostat kontoret
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kontoret_temperature
    above: 0.05
    value_template: '{{ (states("sensor.kontoret_temperature")|float) - (states("input_number.termostat_kontoret")|float)
      }}'
  - platform: numeric_state
    entity_id: sensor.kontoret_temperature
    below: '-0.05'
    value_template: '{{ (states("sensor.kontoret_temperature")|float) - (states("input_number.termostat_kontoret")|float)
      }}'
  - platform: time_pattern
    hours: '*'
    minutes: '15'
    seconds: '0'
    id: backup
  condition: []
  action:
  - service: pyscript.toggle_thermostat
    data:
      thermostat: pyscript.thermostat_kontor
  mode: single
- id: '1631452673858'
  alias: 'Vekking: Sikre lysfade på riktig tidspunkt'
  description: ''
  trigger:
  - platform: state
    entity_id: input_datetime.vekking
  condition: []
  action:
  - service: pyscript.set_wakeup_trans
  mode: single
- id: '1631457413397'
  alias: 'LysFade: Aktivere alarmer neste dag'
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - service: pyscript.set_trans_start_time
    data:
      transition_group: Hoved
  - service: pyscript.set_trans_start_time
    data:
      transition_group: Faste lys
  mode: single
- id: '1631461388472'
  alias: 'Musikk: Av/på anlegg kjøkken'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant 2
      type: keypress
      key: Up
  condition: []
  action:
  - service: remote.send_command
    target:
      entity_id:
      - remote.harmony_hub_gangen
    data:
      device: JVC Mini System
      command: PowerToggle
  mode: single
- id: '1631464549309'
  alias: 'Musikk: Av anlegg bad'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant 2
      type: keypress
      key: Right
  condition:
  - condition: state
    entity_id: input_boolean.status_anlegg_bad
    state: 'on'
  action:
  - service: remote.send_command
    target:
      entity_id:
      - remote.harmony_hub_gangen
    data:
      device: '75887078'
      command: PowerOff
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.status_anlegg_bad
  mode: single
- id: '1631464639339'
  alias: 'Musikk: Av/på anlegg stua'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant 2
      type: keypress
      key: Down
  condition: []
  action:
  - service: remote.send_command
    data:
      device: Yamaha AV Receiver
      command: PowerToggle
    target:
      entity_id: remote.harmony_hub_stua
  - type: toggle
    device_id: 7d62068a7364803a9ff5c1f520dacaab
    entity_id: light.hue_smart_plug_1
    domain: light
  mode: single
- id: '1631464675472'
  alias: 'Musikk: Av/på anlegg soverom'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant 2
      type: keypress
      key: Left
  condition: []
  action:
  - service: remote.send_command
    data:
      device: Teac Home Theater
      command: PowerToggle
    target:
      entity_id: remote.harmony_hub_soverom
  mode: single
- id: '1631467441105'
  alias: 'Musikk: På anlegg bad'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant 2
      type: keypress
      key: Right
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: input_boolean.status_anlegg_bad
      state: 'on'
  action:
  - service: remote.send_command
    target:
      entity_id:
      - remote.harmony_hub_gangen
    data:
      device: '75887078'
      command: PowerOn
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.status_anlegg_bad
  mode: single
- id: '1631511687664'
  alias: 'Vekking: backup for lys soverom'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ now().timestamp() | timestamp_custom(''%H:%M'', true) == (state_attr(''input_datetime.vekking'',
      ''timestamp'') + (15*60)) | timestamp_custom(''%H:%M'', false)}}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.alarm_med_lys
      state: 'on'
    - condition: state
      entity_id: input_boolean.alarm_aktiv
      state: 'on'
    - condition: or
      conditions:
      - condition: not
        conditions:
        - condition: state
          entity_id: light.c_soverom
          state: 'on'
      - condition: not
        conditions:
        - condition: numeric_state
          entity_id: light.c_soverom
          attribute: brightness
          above: '175'
  action:
  - service: light.turn_on
    data:
      brightness: 50
    target:
      entity_id: light.soverom
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    target:
      entity_id: light.soverom
    data:
      transition: 300
      brightness: 255
  mode: single
- id: '1631550050890'
  alias: 'Vekking: øk volumet hvis jeg ikke står opp (første gang)'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ now().timestamp() | timestamp_custom(''%H:%M'', true) == (state_attr(''input_datetime.vekking'',
      ''timestamp'') + (20*60)) | timestamp_custom(''%H:%M'', false)}}'
  condition:
  - condition: state
    entity_id: input_boolean.vekking_pagar
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarm_aktivert_med_lyd
    state: 'on'
  action:
  - service: pyscript.volume_increase
    data:
      fadein_seconds: 30
      device: media_player.godehol
      initial_volume: 0.5
      final_volume: 0.75
  mode: single
- id: '1631550082389'
  alias: 'Vekking: øk volumet hvis jeg ikke står opp (andre gang)'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ now().timestamp() | timestamp_custom(''%H:%M'', true) == (state_attr(''input_datetime.vekking'',
      ''timestamp'') + (30*60)) | timestamp_custom(''%H:%M'', false)}}'
  condition:
  - condition: state
    entity_id: input_boolean.vekking_pagar
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarm_aktivert_med_lyd
    state: 'on'
  action:
  - service: pyscript.volume_increase
    data:
      fadein_seconds: 30
      device: media_player.godehol
      initial_volume: 0.75
      final_volume: 1
  mode: single
- id: '1631555281139'
  alias: 'Radio: NRK P1'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant Pi
      type: keypress
      key: Search
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.godehol
    data:
      media_content_id: https://lyd.nrk.no/nrk_radio_p1_sorlandet_mp3_h
      media_content_type: audio/mp3
      extra:
        metadata:
          metadataType: 0
          title: NRK P1
          images:
          - url: https://play-lh.googleusercontent.com/U5LxZ1tqqcOoQk6igbKN6Xu6iFxP7jbsUq5pryhxqfeMNs1NIkF6UsFJS-FbdPOlEg=s180-rw
  mode: single
- id: '1631983534795'
  alias: 'Vekking_old: 30min før alarmtid (starte lysfade)'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ now().timestamp() | timestamp_custom(''%H:%M'', true) == (state_attr(''input_datetime.vekking'',
      ''timestamp'') - (30*60)) | timestamp_custom(''%H:%M'', false)}}'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_aktiv
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarm_med_lys
    state: 'on'
  action:
  - service: pyscript.start_wakeup_light
  mode: restart
- id: '1631986423032'
  alias: 'Lysfade: Faste lys - start ny gruppe'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.lysfade_start_neste_fastelysfade
  condition: []
  action:
  - service: pyscript.set_current_trans_auto
    data:
      transition_group: Faste lys
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: pyscript.trigger_transition_scene
    data:
      transition_group: Faste lys
  mode: restart
- id: '1632041943235'
  alias: 'Vekking: på alarmtid (alltid)'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.vekking
  condition:
  - condition: state
    entity_id: input_boolean.alarm_aktiv
    state: 'on'
  action:
  - service: pyscript.wakeup_fully
  mode: restart
- id: '1632042306713'
  alias: 'Fjernkontroll: Reagere på knapp'
  description: ''
  trigger:
  - platform: event
    event_type: roku_command
  condition: []
  action:
  - service: pyscript.remote_action_trigger
    data:
      trigger: '{{ trigger }}

        '
  mode: single
- id: '1632823814300'
  alias: 'Lysfade: Faste lys - neste fade'
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.lysfade_neste_trigger_fastelys
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: pyscript.trigger_transition_scene
    data:
      transition_group: Faste lys
  mode: restart
- id: '1632860506560'
  alias: 'Lysfade: Fange opp at lyset blir skrudd på'
  description: ''
  trigger:
  - platform: state
    entity_id: light.stue
    to: 'on'
  - platform: state
    entity_id: light.gang_nede
    to: 'on'
  - platform: state
    entity_id: light.kontor
    to: 'on'
  - platform: state
    entity_id: light.bad
    to: 'on'
  - platform: state
    entity_id: light.kjokken
    to: 'on'
  condition: []
  action:
  - service: pyscript.run_trans_for_turned_on_room
    data:
      trigger: '{{ trigger }}

        '
  mode: parallel
  max: 10
