
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

http:
  server_port: 8123
  #cors_allowed_origins:
  #  - https://google.com
  #  - https://www.home-assistant.io
  ip_ban_enabled: true
  login_attempts_threshold: 10
    
# Text to speech
tts:
  - platform: google_translate
    service_name: google_translate_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include themes.yaml

tradfri:
  host: 192.168.50.53

ifttt:
  key: !secret ifttt_key

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

rest_command: !include rest.yaml

shell_command: !include shell_commands.yaml

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

pyscript: !include pyscript/config.yaml

gramatus:
# roomtoggles:

tellstick:
  host: core-tellstick
  port: [50800, 50801]

sensor: !include sensors.yaml
sensor weather: !include weather.yaml

template: !include templates.yaml

input_boolean: !include input_booleans.yaml
input_datetime: !include input_datetime.yaml

binary_sensor: !include binary_sensors.yaml

logger:
  default: info
  logs:
    homeassistant.setup: warn
    homeassistant.components.binary_sensor: warn
    homeassistant.components.sensor: warn
    homeassistant.components.media_player: warn
    homeassistant.components.cast: warn
    homeassistant.components.cast.media_player: warn
    custom_components.spotcast: warn
    custom_components.harmony: debug
    coap: warn
    homeassistant.components.auth: debug
    homeassistant.components.http.ban: debug
    custom_components.gramatus: debug
    custom_components.roomtoggles: debug
    #homeassistant.components.zeroconf: debug
    #pychromecast: debug
    # My pyscripts
    hue_tools: debug
    fully_actions: debug
    spotify_play: debug
    # Disable info logging from automations running all the time (that usually also has custom logging from my scripts if needed)
    homeassistant.components.automation.termostat_kontoret: warning
    homeassistant.components.automation.vekking_sikre_lysfade_pa_riktig_tidspunkt: warning
    homeassistant.components.automation.lysfade_sikre_tid_fra_vekking_til_arbeidslys: warning
    homeassistant.components.automation.fjernkontroll_reagere_pa_knapp: warning
    homeassistant.components.automation.lysfade_fange_opp_at_lyset_blir_skrudd_pa: warning
  filters:
    pychromecast.controllers:
      - "Receiver:channel_disconnected"
      - "Receiver:setting volume"
    # Invalid logins shows up without acutally there being a problem. Remove from log if we have sufficient reason to believe this is an error.
    # Login from localhost is probably nabu casa
    #homeassistant.components.http.ban:
      #- 'Login attempt or request with invalid authentication from localhost \(127\.0\.0\.1\).*8051_EEA' # Don't log if from NABU CASA and 0851_EEA (one of my tablets)
      #- 'Login attempt or request with invalid authentication from localhost \(127\.0\.0\.1\).*SM-G781B' # Don't log if from NABU CASA and SM-G781B (my cellphone)
      #- 'Login attempt or request with invalid authentication from Torgeir \(192\.168\.50\.100\)' # Don't log if from my laptop
