
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

http:
  server_port: 8123
  #cors_allowed_origins:
  #  - https://google.com
  #  - https://www.home-assistant.io
  ip_ban_enabled: true
  login_attempts_threshold: 10

# Text to speech
tts:
  - platform: google_translate
    service_name: google_translate_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include themes.yaml
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

ifttt:
  key: !secret ifttt_key

# spotify:
#   client_id: !secret spotify_client_id
#   client_secret: !secret spotify_client_secret

rest_command: !include rest.yaml

shell_command: !include shell_commands.yaml

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

pyscript: !include pyscript/config.yaml

gramatus:
# roomtoggles:

tellstick:
  host: core-tellstick
  port: [50800, 50801]

sensor: !include sensors.yaml
mqtt:
  sensor: !include mqtt.yaml

template: !include templates.yaml

input_boolean: !include input_booleans.yaml
input_datetime: !include input_datetime.yaml

binary_sensor: !include binary_sensors.yaml

logger:
  default: info
  logs:
    homeassistant.setup: warn
    homeassistant.components.binary_sensor: warn
    homeassistant.components.sensor: warn
    homeassistant.components.media_player: warn
    homeassistant.components.cast: warn
    homeassistant.components.cast.media_player: warn
    custom_components.spotcast: info
    custom_components.harmony: info
    coap: warn
    homeassistant.components.auth: debug
    homeassistant.components.http.ban: debug
    custom_components.gramatus: debug
    custom_components.roomtoggles: debug
    #homeassistant.components.zeroconf: debug
    pytradfri: info
    pychromecast: info
    # My pyscripts
    hue_tools: debug
    fully_actions: debug
    spotify_play: info
    spotify_services: info
    # custom_components.pyscript.scripts.hue_trans_tools: debug
    # hue_trans_tools: debug
    # Disable info logging from automations running all the time (that usually also has custom logging from my scripts if needed)
    homeassistant.components.automation.termostat_kontoret: warning
    homeassistant.components.automation.vekking_sikre_lysfade_pa_riktig_tidspunkt: warning
    homeassistant.components.automation.lysfade_sikre_tid_fra_vekking_til_arbeidslys: warning
    homeassistant.components.automation.fjernkontroll_reagere_pa_knapp: warning
    homeassistant.components.automation.hue_reagere_pa_knapp: warning
    homeassistant.components.automation.lysfade_fange_opp_at_lyset_blir_skrudd_pa: warning
    homeassistant.components.automation.lysfade_fange_opp_at_lyset_blir_skrudd_av: warning
    homeassistant.components.automation.home_away_leave_home: warning
    homeassistant.components.automation.home_away_come_home: warning
  filters:
    # Closing connection to hue bridge<
    aiohue.v1[192.168.50.52]:
      - "Connection to bridge closed."
    pychromecast.controllers:
      - "Receiver:channel_disconnected"
      - "Receiver:setting volume"
    pychromecast.socket_client:
      - "Received unknown namespace"
      - "Failed to connect to service"
      - "Error communicating with socket, resetting connection"
      - "Error reading from socket."
      - "Connection reestablished!"
      - "Heartbeat timeout, resetting connection"
    homeassistant.components.automation:
      - ": Restarting"
      - ": Running automation actions"
    # Invalid logins shows up without acutally there being a problem. Remove from log if we have sufficient reason to believe this is an error.
    # Login from localhost is probably nabu casa
    #homeassistant.components.http.ban:
      #- 'Login attempt or request with invalid authentication from localhost \(127\.0\.0\.1\).*8051_EEA' # Don't log if from NABU CASA and 0851_EEA (one of my tablets)
      #- 'Login attempt or request with invalid authentication from localhost \(127\.0\.0\.1\).*SM-G781B' # Don't log if from NABU CASA and SM-G781B (my cellphone)
      #- 'Login attempt or request with invalid authentication from Torgeir \(192\.168\.50\.100\)' # Don't log if from my laptop
