- platform: spotcast
  scan_interval: 604800
# - platform: gramatus
# - platform: roomtoggles
# - platform: uptime
#   name: Oppetid HA
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'

# See notes/tellstick.md for information on setting this up
- platform: tellstick
  temperature_scale: "°C"
  # datatype_mask: 1
  only_named:
    - id: 34
      name: Kontoret
    - id: 112
      name: Stua
    - id: 21
      name: Ute
    - id: 83
      name: Kjøkkenet
    - id: 135 # Channel 1
      name: Soverommet
    - id: 151 # Channel 2
      name: Kjeller
    - id: 167 # Channel 3
      name: Gang nede
    - id: 183 # Channel 4
      name: Bad
# Template sensors moved to templates.yaml (modern template: integration)
